/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an account (closed after the first one unless open-registration is enabled) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description Account created; refresh token set as an httpOnly cookie. */
                201: {
                    headers: {
                        "Set-Cookie": components["headers"]["RefreshCookie"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenResponse"];
                    };
                };
                400: components["responses"]["ValidationError"];
                403: components["responses"]["ApiError"];
                409: components["responses"]["ApiError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authenticate with email and password */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Authenticated; refresh token set as an httpOnly cookie. */
                200: {
                    headers: {
                        "Set-Cookie": components["headers"]["RefreshCookie"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenResponse"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["ApiError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate the refresh token and mint a new access token
         * @description Reads the `aether_refresh` cookie; each token is single-use.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description New access token; rotated refresh token set as cookie. */
                200: {
                    headers: {
                        "Set-Cookie": components["headers"]["RefreshCookie"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenResponse"];
                    };
                };
                401: components["responses"]["ApiError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the refresh token and clear its cookie */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Logged out. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The authenticated user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current user. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserResponse"];
                    };
                };
                401: components["responses"]["ApiError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/habits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the user's habits with today's state, streak and last 7 days */
        get: {
            parameters: {
                query: {
                    /** @description The client's local date — the server never guesses timezones. */
                    today: components["parameters"]["Today"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Habits ordered by creation. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HabitResponse"][];
                    };
                };
                401: components["responses"]["ApiError"];
            };
        };
        put?: never;
        /** Create a habit */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateHabitRequest"];
                };
            };
            responses: {
                /** @description Created. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HabitSummary"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["ApiError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/habits/{habitId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a habit and its history */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    habitId: components["parameters"]["HabitId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["ApiError"];
            };
        };
        options?: never;
        head?: never;
        /** Rename a habit */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    habitId: components["parameters"]["HabitId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RenameHabitRequest"];
                };
            };
            responses: {
                /** @description Renamed. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["ValidationError"];
                404: components["responses"]["ApiError"];
            };
        };
        trace?: never;
    };
    "/api/habits/{habitId}/checkins/{date}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Mark the habit done on a day (idempotent; future days refused) */
        put: {
            parameters: {
                query: {
                    /** @description The client's local date — the server never guesses timezones. */
                    today: components["parameters"]["Today"];
                };
                header?: never;
                path: {
                    habitId: components["parameters"]["HabitId"];
                    date: components["parameters"]["CheckinDate"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Marked. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["ApiError"];
                404: components["responses"]["ApiError"];
            };
        };
        post?: never;
        /** Unmark the habit on a day (idempotent) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    habitId: components["parameters"]["HabitId"];
                    date: components["parameters"]["CheckinDate"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Unmarked. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["ApiError"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterRequest: {
            /** Format: email */
            email: string;
            password: string;
            displayName: string;
        };
        LoginRequest: {
            email: string;
            password: string;
        };
        TokenResponse: {
            /** @description JWT, valid for 15 minutes; sent as `Authorization Bearer`. */
            accessToken: string;
            user: components["schemas"]["UserResponse"];
        };
        UserResponse: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            displayName: string;
        };
        CreateHabitRequest: {
            name: string;
        };
        RenameHabitRequest: {
            name: string;
        };
        HabitSummary: {
            /** Format: uuid */
            id: string;
            name: string;
        };
        HabitDay: {
            /** Format: date */
            date: string;
            done: boolean;
        };
        HabitResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            doneToday: boolean;
            currentStreak: number;
            /** @description The last 7 days, oldest first, ending today. */
            week: components["schemas"]["HabitDay"][];
        };
        ApiError: {
            /** @description Stable machine-readable code, e.g. invalid_credentials, registration_closed, email_already_used, invalid_refresh_token, validation_failed. */
            code: string;
            message: string;
            /** @description Per-field messages when code is validation_failed. */
            fields: {
                [key: string]: string;
            };
        };
    };
    responses: {
        /** @description Typed error; `code` is stable and translated by the frontend. */
        ApiError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Bean-validation failure with per-field messages. */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
    };
    parameters: {
        /** @description The client's local date — the server never guesses timezones. */
        Today: string;
        HabitId: string;
        CheckinDate: string;
    };
    requestBodies: never;
    headers: {
        /** @description `aether_refresh` — httpOnly, Secure, SameSite=Strict, path=/api/auth. Never readable by frontend code. */
        RefreshCookie: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
