/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an account (closed after the first one unless open-registration is enabled) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description Account created; refresh token set as an httpOnly cookie. */
                201: {
                    headers: {
                        "Set-Cookie": components["headers"]["RefreshCookie"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenResponse"];
                    };
                };
                400: components["responses"]["ValidationError"];
                403: components["responses"]["ApiError"];
                409: components["responses"]["ApiError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authenticate with email and password */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Authenticated; refresh token set as an httpOnly cookie. */
                200: {
                    headers: {
                        "Set-Cookie": components["headers"]["RefreshCookie"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenResponse"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["ApiError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate the refresh token and mint a new access token
         * @description Reads the `aether_refresh` cookie; each token is single-use.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description New access token; rotated refresh token set as cookie. */
                200: {
                    headers: {
                        "Set-Cookie": components["headers"]["RefreshCookie"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenResponse"];
                    };
                };
                401: components["responses"]["ApiError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the refresh token and clear its cookie */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Logged out. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The authenticated user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current user. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserResponse"];
                    };
                };
                401: components["responses"]["ApiError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/habits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the user's habits with today's state, streak and last 7 days */
        get: {
            parameters: {
                query: {
                    /** @description The client's local date — the server never guesses timezones. */
                    today: components["parameters"]["Today"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Habits ordered by creation. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HabitResponse"][];
                    };
                };
                401: components["responses"]["ApiError"];
            };
        };
        put?: never;
        /** Create a habit */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateHabitRequest"];
                };
            };
            responses: {
                /** @description Created. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HabitSummary"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["ApiError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/habits/{habitId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a habit and its history */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    habitId: components["parameters"]["HabitId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["ApiError"];
            };
        };
        options?: never;
        head?: never;
        /** Rename a habit */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    habitId: components["parameters"]["HabitId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RenameHabitRequest"];
                };
            };
            responses: {
                /** @description Renamed. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["ValidationError"];
                404: components["responses"]["ApiError"];
            };
        };
        trace?: never;
    };
    "/api/habits/{habitId}/checkins/{date}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Mark the habit done on a day (idempotent; future days refused) */
        put: {
            parameters: {
                query: {
                    /** @description The client's local date — the server never guesses timezones. */
                    today: components["parameters"]["Today"];
                };
                header?: never;
                path: {
                    habitId: components["parameters"]["HabitId"];
                    date: components["parameters"]["CheckinDate"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Marked. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["ApiError"];
                404: components["responses"]["ApiError"];
            };
        };
        post?: never;
        /** Unmark the habit on a day (idempotent) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    habitId: components["parameters"]["HabitId"];
                    date: components["parameters"]["CheckinDate"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Unmarked. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["ApiError"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the user's notes, most recently edited first */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Note summaries. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NoteSummary"][];
                    };
                };
                401: components["responses"]["ApiError"];
            };
        };
        put?: never;
        /** Create a note */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateNoteRequest"];
                };
            };
            responses: {
                /** @description Created. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NoteResponse"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["ApiError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notes/{noteId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a note in full */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    noteId: components["parameters"]["NoteId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The note. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NoteResponse"];
                    };
                };
                404: components["responses"]["ApiError"];
            };
        };
        put?: never;
        post?: never;
        /** Delete a note */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    noteId: components["parameters"]["NoteId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["ApiError"];
            };
        };
        options?: never;
        head?: never;
        /** Update a note (partial; omitted fields are left unchanged) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    noteId: components["parameters"]["NoteId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateNoteRequest"];
                };
            };
            responses: {
                /** @description The updated note. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NoteResponse"];
                    };
                };
                400: components["responses"]["ValidationError"];
                404: components["responses"]["ApiError"];
            };
        };
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the user's projects with task counts per state */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Project summaries. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProjectSummary"][];
                    };
                };
                401: components["responses"]["ApiError"];
            };
        };
        put?: never;
        /** Create a project */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateProjectRequest"];
                };
            };
            responses: {
                /** @description Created. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProjectResponse"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["ApiError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{projectId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a project with its tasks */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: components["parameters"]["ProjectId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The project. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProjectResponse"];
                    };
                };
                404: components["responses"]["ApiError"];
            };
        };
        put?: never;
        post?: never;
        /** Delete a project and its tasks */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: components["parameters"]["ProjectId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["ApiError"];
            };
        };
        options?: never;
        head?: never;
        /** Update a project (partial; omitted fields are left unchanged) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: components["parameters"]["ProjectId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateProjectRequest"];
                };
            };
            responses: {
                /** @description The updated project. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProjectResponse"];
                    };
                };
                400: components["responses"]["ValidationError"];
                404: components["responses"]["ApiError"];
            };
        };
        trace?: never;
    };
    "/api/projects/{projectId}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a task to a project (starts as TODO) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: components["parameters"]["ProjectId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateTaskRequest"];
                };
            };
            responses: {
                /** @description Created. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaskResponse"];
                    };
                };
                400: components["responses"]["ValidationError"];
                404: components["responses"]["ApiError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{projectId}/tasks/{taskId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a task */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: components["parameters"]["ProjectId"];
                    taskId: components["parameters"]["TaskId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["ApiError"];
            };
        };
        options?: never;
        head?: never;
        /** Update a task's title or status (partial) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: components["parameters"]["ProjectId"];
                    taskId: components["parameters"]["TaskId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateTaskRequest"];
                };
            };
            responses: {
                /** @description The updated task. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaskResponse"];
                    };
                };
                400: components["responses"]["ValidationError"];
                404: components["responses"]["ApiError"];
            };
        };
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List events overlapping a time window */
        get: {
            parameters: {
                query: {
                    /** @description Window start as an instant (ISO-8601, e.g. 2026-08-20T00:00:00Z). */
                    from: components["parameters"]["RangeFrom"];
                    /** @description Window end as an instant (ISO-8601). Must be after `from`. */
                    to: components["parameters"]["RangeTo"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Events overlapping [from, to), earliest first. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EventResponse"][];
                    };
                };
                400: components["responses"]["ApiError"];
                401: components["responses"]["ApiError"];
            };
        };
        put?: never;
        /** Create an event */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateEventRequest"];
                };
            };
            responses: {
                /** @description Created. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EventResponse"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["ApiError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{eventId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete an event */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    eventId: components["parameters"]["EventId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["ApiError"];
            };
        };
        options?: never;
        head?: never;
        /** Update an event (partial; omitted fields are left unchanged) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    eventId: components["parameters"]["EventId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateEventRequest"];
                };
            };
            responses: {
                /** @description The updated event. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EventResponse"];
                    };
                };
                400: components["responses"]["ValidationError"];
                404: components["responses"]["ApiError"];
            };
        };
        trace?: never;
    };
    "/api/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List transactions in a date range, newest first */
        get: {
            parameters: {
                query: {
                    /** @description Range start as a local date (YYYY-MM-DD), inclusive. */
                    from: components["parameters"]["DateFrom"];
                    /** @description Range end as a local date (YYYY-MM-DD), inclusive. Not before `from`. */
                    to: components["parameters"]["DateTo"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Transactions in [from, to]. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TransactionResponse"][];
                    };
                };
                400: components["responses"]["ApiError"];
                401: components["responses"]["ApiError"];
            };
        };
        put?: never;
        /** Create a transaction */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateTransactionRequest"];
                };
            };
            responses: {
                /** @description Created. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TransactionResponse"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["ApiError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Income, expense, net and per-category totals for a date range */
        get: {
            parameters: {
                query: {
                    /** @description Range start as a local date (YYYY-MM-DD), inclusive. */
                    from: components["parameters"]["DateFrom"];
                    /** @description Range end as a local date (YYYY-MM-DD), inclusive. Not before `from`. */
                    to: components["parameters"]["DateTo"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The summary. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TransactionSummary"];
                    };
                };
                400: components["responses"]["ApiError"];
                401: components["responses"]["ApiError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions/{transactionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a transaction */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    transactionId: components["parameters"]["TransactionId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["ApiError"];
            };
        };
        options?: never;
        head?: never;
        /** Update a transaction (partial; omitted fields are left unchanged) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    transactionId: components["parameters"]["TransactionId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateTransactionRequest"];
                };
            };
            responses: {
                /** @description The updated transaction. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TransactionResponse"];
                    };
                };
                400: components["responses"]["ValidationError"];
                404: components["responses"]["ApiError"];
            };
        };
        trace?: never;
    };
    "/api/ai/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send one message to the assistant and get its reply
         * @description The assistant may read from and write to the other modules while answering; `toolsUsed` names what it actually carried out. It can never delete anything. Both the message and the reply are stored.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChatRequest"];
                };
            };
            responses: {
                /** @description The assistant's reply, already stored. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChatMessage"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["ApiError"];
                /** @description The model provider failed or returned nothing (`ai_unavailable`). */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
                /** @description No API key configured on the server (`ai_not_configured`). */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The stored conversation, oldest first */
        get: {
            parameters: {
                query?: {
                    /** @description How many of the most recent messages to return (1–200). */
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The tail of the conversation, oldest first. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChatMessage"][];
                    };
                };
                401: components["responses"]["ApiError"];
            };
        };
        put?: never;
        post?: never;
        /** Clear the conversation */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Cleared. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["ApiError"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterRequest: {
            /** Format: email */
            email: string;
            password: string;
            displayName: string;
        };
        LoginRequest: {
            email: string;
            password: string;
        };
        TokenResponse: {
            /** @description JWT, valid for 15 minutes; sent as `Authorization Bearer`. */
            accessToken: string;
            user: components["schemas"]["UserResponse"];
        };
        UserResponse: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            displayName: string;
        };
        CreateHabitRequest: {
            name: string;
        };
        RenameHabitRequest: {
            name: string;
        };
        HabitSummary: {
            /** Format: uuid */
            id: string;
            name: string;
        };
        HabitDay: {
            /** Format: date */
            date: string;
            done: boolean;
        };
        HabitResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            doneToday: boolean;
            currentStreak: number;
            /** @description The last 7 days, oldest first, ending today. */
            week: components["schemas"]["HabitDay"][];
        };
        CreateNoteRequest: {
            title?: string;
            content: string;
        };
        /** @description Partial update — omit a field to leave it unchanged. */
        UpdateNoteRequest: {
            title?: string;
            content?: string;
        };
        NoteSummary: {
            /** Format: uuid */
            id: string;
            title: string;
            /** @description First non-blank line of the content, capped — a label for titleless notes. */
            preview: string;
            /** Format: date-time */
            updatedAt: string;
        };
        NoteResponse: {
            /** Format: uuid */
            id: string;
            title: string;
            content: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        /** @enum {string} */
        TaskStatus: "TODO" | "DOING" | "DONE";
        CreateProjectRequest: {
            name: string;
            description?: string;
        };
        /** @description Partial update — omit a field to leave it unchanged. */
        UpdateProjectRequest: {
            name?: string;
            description?: string;
        };
        CreateTaskRequest: {
            title: string;
        };
        /** @description Partial update — omit a field to leave it unchanged. */
        UpdateTaskRequest: {
            title?: string;
            status?: components["schemas"]["TaskStatus"];
        };
        TaskResponse: {
            /** Format: uuid */
            id: string;
            title: string;
            status: components["schemas"]["TaskStatus"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        TaskCounts: {
            todo: number;
            doing: number;
            done: number;
        };
        ProjectSummary: {
            /** Format: uuid */
            id: string;
            name: string;
            taskCounts: components["schemas"]["TaskCounts"];
            /** Format: date-time */
            updatedAt: string;
        };
        ProjectResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            description: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            tasks: components["schemas"]["TaskResponse"][];
        };
        CreateEventRequest: {
            title: string;
            description?: string;
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            endsAt: string;
        };
        /** @description Partial update — omit a field to leave it unchanged. */
        UpdateEventRequest: {
            title?: string;
            description?: string;
            /** Format: date-time */
            startsAt?: string;
            /** Format: date-time */
            endsAt?: string;
        };
        EventResponse: {
            /** Format: uuid */
            id: string;
            title: string;
            description: string;
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            endsAt: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        /** @enum {string} */
        TransactionType: "INCOME" | "EXPENSE";
        CreateTransactionRequest: {
            type: components["schemas"]["TransactionType"];
            /** Format: int64 */
            amountCents: number;
            category?: string;
            description?: string;
            /** Format: date */
            date: string;
        };
        /** @description Partial update — omit a field to leave it unchanged. */
        UpdateTransactionRequest: {
            type?: components["schemas"]["TransactionType"];
            /** Format: int64 */
            amountCents?: number;
            category?: string;
            description?: string;
            /** Format: date */
            date?: string;
        };
        TransactionResponse: {
            /** Format: uuid */
            id: string;
            type: components["schemas"]["TransactionType"];
            /** Format: int64 */
            amountCents: number;
            category: string;
            description: string;
            /** Format: date */
            date: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CategoryTotal: {
            category: string;
            type: components["schemas"]["TransactionType"];
            /** Format: int64 */
            totalCents: number;
        };
        TransactionSummary: {
            /** Format: int64 */
            incomeCents: number;
            /** Format: int64 */
            expenseCents: number;
            /**
             * Format: int64
             * @description income − expense; may be negative
             */
            netCents: number;
            byCategory: components["schemas"]["CategoryTotal"][];
        };
        ChatRequest: {
            message: string;
            /**
             * Format: date
             * @description The client's local date — the server never guesses timezones.
             */
            today: string;
            /** @description The client's offset from UTC in minutes, east positive (i.e. `-new Date().getTimezoneOffset()`). */
            offsetMinutes: number;
        };
        /** @enum {string} */
        ChatRole: "USER" | "ASSISTANT";
        ChatMessage: {
            /** Format: uuid */
            id: string;
            role: components["schemas"]["ChatRole"];
            content: string;
            /** @description Names of the tools the assistant successfully ran for this reply, e.g. create_habit. Empty for anything the user wrote. */
            toolsUsed: string[];
            /** Format: date-time */
            createdAt: string;
        };
        ApiError: {
            /** @description Stable machine-readable code, e.g. invalid_credentials, registration_closed, email_already_used, invalid_refresh_token, validation_failed. */
            code: string;
            message: string;
            /** @description Per-field messages when code is validation_failed. */
            fields: {
                [key: string]: string;
            };
        };
    };
    responses: {
        /** @description Typed error; `code` is stable and translated by the frontend. */
        ApiError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Bean-validation failure with per-field messages. */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
    };
    parameters: {
        /** @description Range start as a local date (YYYY-MM-DD), inclusive. */
        DateFrom: string;
        /** @description Range end as a local date (YYYY-MM-DD), inclusive. Not before `from`. */
        DateTo: string;
        TransactionId: string;
        /** @description Window start as an instant (ISO-8601, e.g. 2026-08-20T00:00:00Z). */
        RangeFrom: string;
        /** @description Window end as an instant (ISO-8601). Must be after `from`. */
        RangeTo: string;
        EventId: string;
        ProjectId: string;
        TaskId: string;
        NoteId: string;
        /** @description The client's local date — the server never guesses timezones. */
        Today: string;
        HabitId: string;
        CheckinDate: string;
    };
    requestBodies: never;
    headers: {
        /** @description `aether_refresh` — httpOnly, Secure, SameSite=Strict, path=/api/auth. Never readable by frontend code. */
        RefreshCookie: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
